//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("STC.Resources.AppResources.ar", typeof(AppResources_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        internal static string NotesPlaceholder {
            get {
                return ResourceManager.GetString("NotesPlaceholder", resourceCulture);
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Inquiries {
            get {
                return ResourceManager.GetString("Inquiries", resourceCulture);
            }
        }
        
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        internal static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string DidntFindQuestion {
            get {
                return ResourceManager.GetString("DidntFindQuestion", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Hotline {
            get {
                return ResourceManager.GetString("Hotline", resourceCulture);
            }
        }
        
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        internal static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        internal static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        internal static string WaitingApproval {
            get {
                return ResourceManager.GetString("WaitingApproval", resourceCulture);
            }
        }
        
        internal static string DismissAll {
            get {
                return ResourceManager.GetString("DismissAll", resourceCulture);
            }
        }
        
        internal static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        internal static string RecentNotifications {
            get {
                return ResourceManager.GetString("RecentNotifications", resourceCulture);
            }
        }
        
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        internal static string YourRequests {
            get {
                return ResourceManager.GetString("YourRequests", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string LoginStc {
            get {
                return ResourceManager.GetString("LoginStc", resourceCulture);
            }
        }
        
        internal static string Contiune {
            get {
                return ResourceManager.GetString("Contiune", resourceCulture);
            }
        }
        
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        internal static string ConfirmEmailAndSms {
            get {
                return ResourceManager.GetString("ConfirmEmailAndSms", resourceCulture);
            }
        }
        
        internal static string VerifyAccount {
            get {
                return ResourceManager.GetString("VerifyAccount", resourceCulture);
            }
        }
        
        internal static string RegisterQuote {
            get {
                return ResourceManager.GetString("RegisterQuote", resourceCulture);
            }
        }
        
        internal static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone number", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string CheckFaq {
            get {
                return ResourceManager.GetString("CheckFaq", resourceCulture);
            }
        }
        
        internal static string InquiriesTabQuote {
            get {
                return ResourceManager.GetString("InquiriesTabQuote", resourceCulture);
            }
        }
        
        internal static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        internal static string NewInquiry {
            get {
                return ResourceManager.GetString("NewInquiry", resourceCulture);
            }
        }
        
        internal static string RequestsTabQuote {
            get {
                return ResourceManager.GetString("RequestsTabQuote", resourceCulture);
            }
        }
        
        internal static string SeeYourInquiries {
            get {
                return ResourceManager.GetString("SeeYourInquiries", resourceCulture);
            }
        }
        
        internal static string SeeYourRequests {
            get {
                return ResourceManager.GetString("SeeYourRequests", resourceCulture);
            }
        }
        
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        internal static string HowCanHelp {
            get {
                return ResourceManager.GetString("HowCanHelp", resourceCulture);
            }
        }
        
        internal static string InquiriesHomeQuote {
            get {
                return ResourceManager.GetString("InquiriesHomeQuote", resourceCulture);
            }
        }
        
        internal static string RequestHomeQuote {
            get {
                return ResourceManager.GetString("RequestHomeQuote", resourceCulture);
            }
        }
        
        internal static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        internal static string EmailorPhone {
            get {
                return ResourceManager.GetString("EmailorPhone", resourceCulture);
            }
        }
        
        internal static string ForgetPassowordMultiLine {
            get {
                return ResourceManager.GetString("ForgetPassowordMultiLine", resourceCulture);
            }
        }
        
        internal static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        internal static string YouCanChange {
            get {
                return ResourceManager.GetString("YouCanChange", resourceCulture);
            }
        }
        
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        internal static string EnterCodeMobile {
            get {
                return ResourceManager.GetString("EnterCodeMobile", resourceCulture);
            }
        }
        
        internal static string EnterCodeEmail {
            get {
                return ResourceManager.GetString("EnterCodeEmail", resourceCulture);
            }
        }
        
        internal static string VerifySMSQuote {
            get {
                return ResourceManager.GetString("VerifySMSQuote", resourceCulture);
            }
        }
        
        internal static string WrongNumber {
            get {
                return ResourceManager.GetString("WrongNumber", resourceCulture);
            }
        }
        
        internal static string DidntReceiveCode {
            get {
                return ResourceManager.GetString("DidntReceiveCode", resourceCulture);
            }
        }
        
        internal static string SendAgain {
            get {
                return ResourceManager.GetString("SendAgain", resourceCulture);
            }
        }
        
        internal static string SMSCode {
            get {
                return ResourceManager.GetString("SMSCode", resourceCulture);
            }
        }
        
        internal static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        internal static string ChooseTheFilesRequired {
            get {
                return ResourceManager.GetString("ChooseTheFilesRequired", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string NewRequestQuote {
            get {
                return ResourceManager.GetString("NewRequestQuote", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        internal static string NumberAttachmentsValidation {
            get {
                return ResourceManager.GetString("NumberAttachmentsValidation", resourceCulture);
            }
        }
        
        internal static string ExtensionValidation {
            get {
                return ResourceManager.GetString("ExtensionValidation", resourceCulture);
            }
        }
        
        internal static string SizeValidation {
            get {
                return ResourceManager.GetString("SizeValidation", resourceCulture);
            }
        }
        
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        internal static string SlideTo {
            get {
                return ResourceManager.GetString("SlideTo", resourceCulture);
            }
        }
        
        internal static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        internal static string UploadNow {
            get {
                return ResourceManager.GetString("UploadNow", resourceCulture);
            }
        }
        
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        internal static string WhenYouSlideAccept {
            get {
                return ResourceManager.GetString("WhenYouSlideAccept", resourceCulture);
            }
        }
        
        internal static string YourSignature {
            get {
                return ResourceManager.GetString("YourSignature", resourceCulture);
            }
        }
        
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        internal static string AboutUs1 {
            get {
                return ResourceManager.GetString("AboutUs1", resourceCulture);
            }
        }
        
        internal static string AboutUs2 {
            get {
                return ResourceManager.GetString("AboutUs2", resourceCulture);
            }
        }
        
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        internal static string OurVision {
            get {
                return ResourceManager.GetString("OurVision", resourceCulture);
            }
        }
        
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        internal static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
        
        internal static string AccessControl {
            get {
                return ResourceManager.GetString("AccessControl", resourceCulture);
            }
        }
        
        internal static string AppApperence {
            get {
                return ResourceManager.GetString("AppApperence", resourceCulture);
            }
        }
        
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string GeneralNotifications {
            get {
                return ResourceManager.GetString("GeneralNotifications", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string SettingsQuote {
            get {
                return ResourceManager.GetString("SettingsQuote", resourceCulture);
            }
        }
        
        internal static string UserFingerprint {
            get {
                return ResourceManager.GetString("UserFingerprint", resourceCulture);
            }
        }
        
        internal static string Privacy_Statements {
            get {
                return ResourceManager.GetString("Privacy Statements", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string STCHomePage {
            get {
                return ResourceManager.GetString("STCHomePage", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        internal static string ContractAgreement {
            get {
                return ResourceManager.GetString("ContractAgreement", resourceCulture);
            }
        }
        
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        internal static string AccessDetials {
            get {
                return ResourceManager.GetString("AccessDetials", resourceCulture);
            }
        }
        
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        internal static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string NationalAddress {
            get {
                return ResourceManager.GetString("NationalAddress", resourceCulture);
            }
        }
        
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        internal static string YourInquiries {
            get {
                return ResourceManager.GetString("YourInquiries", resourceCulture);
            }
        }
        
        internal static string PrivacyStatements {
            get {
                return ResourceManager.GetString("PrivacyStatements", resourceCulture);
            }
        }
        
        internal static string CodeSentSuccessfully {
            get {
                return ResourceManager.GetString("CodeSentSuccessfully", resourceCulture);
            }
        }
        
        internal static string FillRequiredFields {
            get {
                return ResourceManager.GetString("FillRequiredFields", resourceCulture);
            }
        }
        
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string InquiryLbl {
            get {
                return ResourceManager.GetString("InquiryLbl", resourceCulture);
            }
        }
        
        internal static string CallMe {
            get {
                return ResourceManager.GetString("CallMe", resourceCulture);
            }
        }
        
        internal static string ConfirmPasswordChange {
            get {
                return ResourceManager.GetString("ConfirmPasswordChange", resourceCulture);
            }
        }
        
        internal static string MakeStrong {
            get {
                return ResourceManager.GetString("MakeStrong", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string ResendSMS {
            get {
                return ResourceManager.GetString("ResendSMS", resourceCulture);
            }
        }
        
        internal static string SetNewPasswordML {
            get {
                return ResourceManager.GetString("SetNewPasswordML", resourceCulture);
            }
        }
        
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        internal static string VerifyPassword {
            get {
                return ResourceManager.GetString("VerifyPassword", resourceCulture);
            }
        }
        
        internal static string VerifyEmailQuote {
            get {
                return ResourceManager.GetString("VerifyEmailQuote", resourceCulture);
            }
        }
        
        internal static string CongratulationsPasswordChanged {
            get {
                return ResourceManager.GetString("CongratulationsPasswordChanged", resourceCulture);
            }
        }
        
        internal static string CongratulationsVerified {
            get {
                return ResourceManager.GetString("CongratulationsVerified", resourceCulture);
            }
        }
        
        internal static string NewPasswordSaved {
            get {
                return ResourceManager.GetString("NewPasswordSaved", resourceCulture);
            }
        }
        
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string SignHere {
            get {
                return ResourceManager.GetString("SignHere", resourceCulture);
            }
        }
        
        internal static string EamilRequiredMsg {
            get {
                return ResourceManager.GetString("EamilRequiredMsg", resourceCulture);
            }
        }
        
        internal static string PasswordRequiredMsg {
            get {
                return ResourceManager.GetString("PasswordRequiredMsg", resourceCulture);
            }
        }
        
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        internal static string VerifyUsing {
            get {
                return ResourceManager.GetString("VerifyUsing", resourceCulture);
            }
        }
        
        internal static string NoMessages {
            get {
                return ResourceManager.GetString("NoMessages", resourceCulture);
            }
        }
        
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string CongratulationsRegister {
            get {
                return ResourceManager.GetString("CongratulationsRegister", resourceCulture);
            }
        }
        
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        internal static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        internal static string FullNameReuquired {
            get {
                return ResourceManager.GetString("FullNameReuquired", resourceCulture);
            }
        }
        
        internal static string EmailorPasswordInCorrect {
            get {
                return ResourceManager.GetString("EmailorPasswordInCorrect", resourceCulture);
            }
        }
        
        internal static string PassowrdContains {
            get {
                return ResourceManager.GetString("PassowrdContains", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string UnSavedChanges {
            get {
                return ResourceManager.GetString("UnSavedChanges", resourceCulture);
            }
        }
        
        internal static string unSavedChangesQuote {
            get {
                return ResourceManager.GetString("unSavedChangesQuote", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string PassowrdNotMatched {
            get {
                return ResourceManager.GetString("PassowrdNotMatched", resourceCulture);
            }
        }
        
        internal static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        internal static string InvalidMobile {
            get {
                return ResourceManager.GetString("InvalidMobile", resourceCulture);
            }
        }
        
        internal static string invalidName {
            get {
                return ResourceManager.GetString("invalidName", resourceCulture);
            }
        }
        
        internal static string MobileMaxLength {
            get {
                return ResourceManager.GetString("MobileMaxLength", resourceCulture);
            }
        }
        
        internal static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        internal static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        internal static string EnterValidOTP {
            get {
                return ResourceManager.GetString("EnterValidOTP", resourceCulture);
            }
        }
        
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        internal static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        internal static string CameraAccessDenied {
            get {
                return ResourceManager.GetString("CameraAccessDenied", resourceCulture);
            }
        }
        
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        internal static string VerficationSuccessed {
            get {
                return ResourceManager.GetString("VerficationSuccessed", resourceCulture);
            }
        }
        
        internal static string ProfilePictureUpdated {
            get {
                return ResourceManager.GetString("ProfilePictureUpdated", resourceCulture);
            }
        }
        
        internal static string SuccessfulRequest {
            get {
                return ResourceManager.GetString("SuccessfulRequest", resourceCulture);
            }
        }
        
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        internal static string SameName {
            get {
                return ResourceManager.GetString("SameName", resourceCulture);
            }
        }
        
        internal static string SameData {
            get {
                return ResourceManager.GetString("SameData", resourceCulture);
            }
        }
        
        internal static string InvalidAttachmentTitle {
            get {
                return ResourceManager.GetString("InvalidAttachmentTitle", resourceCulture);
            }
        }
        
        internal static string ChooseAttachment {
            get {
                return ResourceManager.GetString("ChooseAttachment", resourceCulture);
            }
        }
        
        internal static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        internal static string NoInquiries {
            get {
                return ResourceManager.GetString("NoInquiries", resourceCulture);
            }
        }
        
        internal static string NoContract {
            get {
                return ResourceManager.GetString("NoContract", resourceCulture);
            }
        }
        
        internal static string CanNotOpenLink {
            get {
                return ResourceManager.GetString("CanNotOpenLink", resourceCulture);
            }
        }
        
        internal static string FileDonwloadedSuccessfully {
            get {
                return ResourceManager.GetString("FileDonwloadedSuccessfully", resourceCulture);
            }
        }
        
        internal static string NoNextRequest {
            get {
                return ResourceManager.GetString("NoNextRequest", resourceCulture);
            }
        }
        
        internal static string NoPreviouseRequest {
            get {
                return ResourceManager.GetString("NoPreviouseRequest", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string MustSign {
            get {
                return ResourceManager.GetString("MustSign", resourceCulture);
            }
        }
        
        internal static string ContractUpdated {
            get {
                return ResourceManager.GetString("ContractUpdated", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        internal static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        internal static string GotoLogin {
            get {
                return ResourceManager.GetString("GotoLogin", resourceCulture);
            }
        }
        
        internal static string EmailTxt {
            get {
                return ResourceManager.GetString("EmailTxt", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string FileNotDonwloaded {
            get {
                return ResourceManager.GetString("FileNotDonwloaded", resourceCulture);
            }
        }
        
        internal static string PermissionRequired {
            get {
                return ResourceManager.GetString("PermissionRequired", resourceCulture);
            }
        }
        
        internal static string PermissionRequiredMsg {
            get {
                return ResourceManager.GetString("PermissionRequiredMsg", resourceCulture);
            }
        }
        
        internal static string TypeMessage {
            get {
                return ResourceManager.GetString("TypeMessage", resourceCulture);
            }
        }
        
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
    }
}
